services:
  vue:
    image: node:current-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run serve"
    ports:
      - "80:80"
      - "443:443"
networks:
    default:
        external:
            name: bridge
