version: '3'

services:
  vue:
    image: node:current-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run serve"
    ports:
      - "80:80"
      - "443:443"
# networks:
#    vue:
#       name: vue
#       driver: macvlan